---
openapi: "3.0.1"
info:
  title: "Automotive Retail Systems API"
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: "Platform Architecture Team"
    url: "www.starstandard.org"
    email: "pescobar@starstandard.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    ControlAccountReference:
      type: "object"
      properties:
        control_account_reference_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value"
        control_account_reference_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value"
        control_account_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        system_codes:
          $ref: "#/components/schemas/Codes"
        control_account:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
      description: "Reference link to the control account."
      types:
      - "object"
    ControlAccountReferences:
      type: "array"
      items:
        $ref: "#/components/schemas/ControlAccountReference"
    EntryResourceTypes:
      type: "string"
      description: "types of entry resources."
      enum:
      - "CUSTOM"
      - "PAYROLL_EARNING"
      - "TAX"
      - "FEE"
      - "LENDER"
      - "TRADE_IN"
      - "DISCOUNT"
      - "INCENTIVE"
      - "RESIDUAL"
      - "DEPOSIT"
      - "DUE_ON"
      - "PAYMENT"
      - "PAYABLE"
      - "EXPENSE"
      - "RECEIVABLE"
      - "COST_OF_SALE"
      - "SALE"
      - "INVENTORY"
      - "INCOME"
      - "CONTRACTS_IN_TRANSIT"
      - "DEALER_VALUE"
      - "INSURANCE"
      - "SERVICE"
      - "PRODUCT"
      - "CONTRACT"
    FinancialFlowStatusTypes:
      type: "string"
      description: "types of financial flow status."
      enum:
      - "DRAFT"
      - "PENDING_APPROVAL"
      - "POSTED"
      - "FAILED"
      - "REFUNDED"
      - "APPROVED"
      - "DECLINED"
      - "REJECTED"
      - "INITIATING"
      - "COMPLETE"
      - "ACTIVE"
      - "INACTIVE"
      - "INVALID"
      - "ABANDON"
      - "CANCELLED"
      - "SALES_HOLD"
      - "PAYMENT_HOLD"
      - "FINANCE_HOLD"
      - "CUSTOMER_HOLD"
    GeneralLedgerReference:
      type: "object"
      properties:
        general_ledger_reference_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique reference value"
        general_ledger_reference_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique reference value"
        general_ledger_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique reference value"
        context:
          type: "string"
          description: "Context or domain of the reference"
        system_codes:
          $ref: "#/components/schemas/Codes"
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the event occurred."
          format: "date-time"
      description: "Reference to the primary General Ledger."
      types:
      - "object"
    GeneralLedgerReferences:
      type: "array"
      items:
        $ref: "#/components/schemas/GeneralLedgerReference"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value"
        identifier_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Business key for the identifier"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "Unique identification key for the record."
      types:
      - "object"
    Identifiers:
      type: "array"
      items:
        $ref: "#/components/schemas/Identifier"
    JournalEntries:
      type: "array"
      items:
        $ref: "#/components/schemas/JournalEntry"
    JournalEntry:
      type: "object"
      properties:
        journal_entry_id:
          type: "string"
          description: "natural immutable identifier"
        journal_entry_key:
          type: "string"
          description: "natural immutable identifier"
        entry_sequence:
          type: "string"
          description: "entry sequence"
        financial_transaction_key:
          type: "string"
          description: "Unique identifier of the financial trans..."
        control_account_references:
          $ref: "#/components/schemas/ControlAccountReferences"
        general_ledger_references:
          $ref: "#/components/schemas/GeneralLedgerReferences"
        subsidiary_ledger_reference:
          $ref: "#/components/schemas/SubsidiaryLedgerReference"
        desc:
          type: "string"
          description: "A description for the journal entry."
          example: "Sales - Extended Service Contract"
        detail_sequence:
          type: "string"
          description: "A sequence number for batch updates for ..."
        journal_type:
          $ref: "#/components/schemas/JournalTypes"
        org_href:
          type: "string"
          description: "A reference link to the organization ass..."
          format: "href"
          example: "1"
        org_id:
          type: "string"
          description: "The ID of the organization (cost or prof..."
          example: "1"
        org_type:
          $ref: "#/components/schemas/OrganizationTypes"
        money:
          $ref: "#/components/schemas/Money"
        entry_reference_account_desc:
          type: "string"
          description: "A description of the reference account."
          example: "Cost of Goods"
        reference_account_id:
          type: "string"
          description: "The ID of the reference account."
          example: "54322"
        resource_href:
          type: "string"
          description: "A unique identifier (link) to the root r..."
          format: "href"
        resource_id:
          type: "string"
          description: "The unique identifier of the root resour..."
          example: "543"
        resource_type:
          $ref: "#/components/schemas/EntryResourceTypes"
        gl_segments:
          $ref: "#/components/schemas/Identifiers"
        accounting_period_key:
          type: "string"
          description: "The ID of the reference account for the ..."
      description: "Record of a financial transaction in the ledger."
      types:
      - "object"
    JournalEntryTransaction:
      type: "object"
      properties:
        journal_entry_transaction_id:
          type: "string"
          description: "A unique system-generated identifier for..."
          example: "gle_700123"
        journal_entry_transaction_key:
          type: "string"
          description: "A unique system-generated identifier for..."
          example: "gle_700123"
        provider_key:
          type: "string"
          description: "Identifier for the payroll system or pro..."
          example: "PAY-PRO-2"
        cycle_id:
          type: "string"
          description: "Identifier for the specific payroll cycl..."
          example: "2025-09-WEEK2"
        entry_date:
          type: "string"
          description: "The date the journal entry was recorded ..."
          format: "date"
          example: "2025-09-30T00:00:00Z"
        total_debit_amount:
          $ref: "#/components/schemas/Money"
        total_credit_amount:
          $ref: "#/components/schemas/Money"
        is_balanced:
          type: "boolean"
          description: "A flag indicating if the total debits eq..."
          example: "true"
        financial_flow_status_type:
          $ref: "#/components/schemas/FinancialFlowStatusTypes"
        journal_entries:
          $ref: "#/components/schemas/JournalEntries"
        accounting_period_key:
          type: "string"
          description: "The ID of the reference account for the ..."
      description: "Details of the specific journal transaction."
      types:
      - "object"
    JournalTypes:
      type: "string"
      description: "types of journals."
      enum:
      - "DEBIT"
      - "CREDIT"
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
        value:
          type: "string"
          description: "The monetary value."
      description: "Monetary value and currency information."
      types:
      - "object"
    OrganizationTypes:
      type: "string"
      description: "types of organizations."
      enum:
      - "CORPORATION"
      - "DIVISION"
      - "FRANCHISE"
      - "GROUP"
      - "STORE"
      - "DEALERSHIP"
      - "BRANCH"
      - "DEPARTMENT"
      - "SECTION"
      - "TEAM"
      - "OTHER"
    SubsidiaryLedgerReference:
      type: "object"
      properties:
        subsidiary_ledger_reference_id:
          type: "string"
          description: "Unique identifier for the Subsidiary Led..."
        subsidiary_ledger_reference_key:
          type: "string"
          description: "Business key for the Subsidiary Ledger r..."
        subsidiary_ledger_transaction_key:
          type: "string"
          description: "The key of the referenced Subsidiary Led..."
        context:
          type: "string"
          description: "Context or domain of the Sub-Ledger tran..."
        system_codes:
          $ref: "#/components/schemas/Codes"
        subsidiary_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the Journal Entry refe..."
          format: "date-time"
      description: "Reference to a supporting sub-ledger."
      types:
      - "object"
