openapi: 3.0.1
info:
  title: Automotive Retail Systems API
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: Platform Architecture Team
    url: www.starstandard.org
    email: pescobar@starstandard.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths: {}
components:
  schemas:
    Codes:
      type: array
      items:
        type: string
    CreditAuthorization:
      type: object
      properties:
        credit_authorization_id:
          type: string
          description: Unique system identifier for the Credit ...
        credit_authorization_key:
          type: string
          description: Natural business key for the authorizati...
        credit_authorization_status_type:
          $ref: "#/components/schemas/CreditAuthorizationStatusTypes"
        credit_authorization_type:
          $ref: "#/components/schemas/CreditAuthorizationTypes"
        invoice_price:
          $ref: "#/components/schemas/Price"
        dealer_price:
          $ref: "#/components/schemas/Price"
        auth_number:
          type: string
          description: The approval number returned by the exte...
        auth_code:
          type: string
          description: Specific response code from the financia...
        auth_date_time:
          type: string
          description: Timestamp when the authorization was pro...
          format: date-time
        pre_auth_num:
          type: string
          description: The fund verification or pre-authorizati...
        party_references:
          $ref: "#/components/schemas/PartyReferences"
        source_key:
          type: string
          description: Identification of the originating system...
        purchase_order_num:
          type: string
          description: Associated Purchase Order number.
        auth_reasons:
          $ref: "#/components/schemas/Codes"
        program:
          $ref: "#/components/schemas/Program"
        auth_amount:
          $ref: "#/components/schemas/Money"
        language:
          type: string
          description: "English, Spanish"
        address_verification:
          type: string
          description: Context or domain of the reference.
        context:
          type: string
          description: Context or domain of the reference.
        transaction_number:
          type: string
          description: Context or domain of the reference.
        invoice_types:
          $ref: "#/components/schemas/InvoiceTypes"
      description: credit.authorization.desc
    CreditAuthorizationStatusTypes:
      type: string
      description: types of credit authorization status.
      enum:
      - VALIDATION
      - FUND_VERIFICATION
      - PENDING_EXTERNAL
      - AUTHORIZED
      - PARTIALLY_AUTHORIZED
      - CAPTURED
      - VOIDED
      - EXPIRED
      - DECLINED
      - FAILED_TECHNICAL
      - FRAUD_REJECTED
      - OTHER
    CreditAuthorizationTypes:
      type: string
      description: types of credit authorizations.
      enum:
      - STANDARD_AUTH
      - PRE_AUTH
      - MEMO
      - NA
      - OTHER
    CurrencyExchange:
      type: object
      properties:
        currency_exchange_id:
          type: string
          description: Unique system identifier for the currenc...
        currency_exchange_key:
          type: string
          description: Natural key or business identifier for t...
        source_currency:
          type: string
          description: Human-readable display value for the sou...
        target_currency:
          type: string
          description: Human-readable display value for the sou...
        currency_exchange_desc:
          type: string
          description: A descriptive title for the currencyExch...
        exchange_rate:
          type: string
          description: Human-readable display value for the sou...
        rate_date_time:
          type: string
          description: The date and time the rate was associate...
          format: date-time
      description: currency.exchange.desc
    EffectivePeriod:
      type: object
      properties:
        effective_period_key:
          type: string
          description: Unique key identifying the effective per...
        active_indicator:
          type: boolean
          description: Indicator if the period is currently act...
        exclusive_indicator:
          type: boolean
          description: Indicator if the period is exclusive
        start_date_time:
          type: string
          description: Start date and time of the effective per...
          format: date-time
        complete_date_time:
          type: string
          description: Completion date and time of the effectiv...
          format: date-time
        duration_uom_type:
          $ref: "#/components/schemas/DurationUOMTypes"
        duration_value:
          type: string
          description: Value of the duration
        recur_uom_type:
          $ref: "#/components/schemas/DurationUOMTypes"
        recur_count:
          type: string
          description: Count of recurrence
        recur_values:
          $ref: "#/components/schemas/Codes"
        recur_criteria:
          type: string
          description: Criteria defining recurrence
        recur_indicator:
          type: boolean
          description: Indicator if recurrence is enabled
      description: effective.period.desc
    Identifier:
      type: object
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          type: string
          description: Unique identifier value
        identifier_key:
          maxLength: 50
          minLength: 5
          type: string
          description: Business key for the identifier
        context:
          type: string
          description: Context or domain of the identifier
        value:
          type: string
          description: The monetary or hours-based value of the...
        detail:
          type: string
          description: The monetary or hours-based value of the...
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: identifier.desc
    InvoiceTypes:
      type: string
      description: types of invoices.
      enum:
      - INVOICE
      - STANDARD
      - CREDIT_MEMO
      - DEBIT_MEMO
      - PRO_FORMA
      - COMMERCIAL
      - VEHICLE_SALE
      - SERVICE
      - PARTS
      - LEASE
      - FINANCE_CHARGE
      - WARRANTY_CLAIM
      - INSURANCE_CLAIM
      - STATEMENT
      - ADVANCE
      - FINAL
    List:
      type: array
      items:
        $ref: "#/components/schemas/PriceTypes"
    Money:
      type: object
      properties:
        money_key:
          type: string
          description: The unique key for the monetary value.
        money_id:
          type: string
          description: The unique ID for the monetary value.
        currency_code:
          type: string
          description: "ISO currency code, e.g., 'USD'."
        display_value:
          type: string
          description: The locale-specific display format for t...
        locale:
          type: string
          description: "The locale code (e.g., en-US, fr-FR)."
        value:
          type: string
          description: The monetary value.
        currency_exchange:
          $ref: "#/components/schemas/CurrencyExchange"
      description: money.desc
    PartyReference:
      type: object
      properties:
        party_reference_id:
          type: string
          description: Unique identifier value
        party_reference_key:
          type: string
          description: Unique identifier value
        party_key:
          type: string
          description: Unique identifier value
        party_reference_type:
          type: string
          description: Unique identifier value
        context:
          type: string
          description: Context or domain of the identifier
        account_number:
          type: string
          description: Account Number
        party_relationship_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PartyRelationshipTypes"
        system_codes:
          $ref: "#/components/schemas/Codes"
        rule_codes:
          $ref: "#/components/schemas/Codes"
        party:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: string
          description: The date and time the event occurred.
          format: date-time
        duration:
          $ref: "#/components/schemas/EffectivePeriod"
      description: party.reference.desc
    PartyReferences:
      type: array
      items:
        $ref: "#/components/schemas/PartyReference"
    PartyRelationshipTypes:
      type: string
      description: types of party relationships.
      enum:
      - CORPORATION
      - GROUP
      - STORE
      - BRANCH
      - DEPARTMENT
      - SECTION
      - TEAM
      - DEALERSHIP
      - THIRD_PARTY
      - VENDOR
      - SUPPLIER
      - PARTNER_ORGANIZATION
      - AFFILIATE
      - DISTRIBUTOR
      - MANUFACTURER
      - SERVICE_PROVIDER
      - EMPLOYER
      - INTERNAL_ORGANIZATION
      - COST_CENTER
      - FREIGHT_FORWARDER
      - BUYER
      - REGULATOR
      - GOVERNMENT_AGENCY
      - NON_PROFIT
      - FRANCHISE
      - SUBSIDIARY
      - DIVISION
      - JOINT_VENTURE
      - AUDITOR
      - ACTOR
      - ACCOUNTABLE
      - RESPONSIBLE
      - CONSULT
      - NOTIFY
      - EXECUTE
      - PART_OF
      - MEMBERSHIP
      - COMPOSED_IN
      - CUSTOMER
      - CO_SIGNER
      - SPOUSE
      - PARENT
      - CHILD
      - SIBLING
      - LEGAL_GUARDIAN
      - DEPENDENT
      - EMERGENCY_CONTACT
      - FAMILY_MEMBER
      - FRIEND
      - ACQUAINTANCE
      - ASSOCIATE
      - EX_SPOUSE
      - PROFESSIONAL_CONTACT
      - MANAGER
      - CO_WORKER
      - FINANCIAL_ADVISOR
      - SELF
      - ROMANTIC_PARTNER
      - OTHER_FAMILY
      - CAREGIVER
      - MENTOR
      - MENTEE
      - HEIR
      - TRUSTEE_PERSON
      - REFERENCE_PERSONAL
      - REFERENCE_PROFESSIONAL
      - AGENT
      - BENEFICIARY
      - GUARANTOR
      - EMPLOYEE
      - CONTRACTOR
      - OWNER
      - BUSINESS_PARTNER
      - SERVICE_CONSUMER
      - POLITICAL_AFFILIATE
      - ADVISOR_CONSULTANT
      - PROXY
      - SHAREHOLDER
      - INVESTOR
      - CUSTODIAN
      - SOLD_TO
      - SHIP_TO
      - PAYER
      - PAYEE
      - GIFT_TO
      - LOAN_PROVIDER
      - CREDIT_CARD_PROVIDER
      - LESSEE
      - LESSOR
      - INSURED
      - INSURER
      - UNDERWRITER
      - RECIPIENT
      - TRANSACTION_FROM
      - TRANSACTION_TO
      - REMOVE
      - OTHER
    PayTypes:
      type: string
      description: types of pays.
      enum:
      - CUSTOMER_PAY
      - WARRANTY
      - INTERNAL
      - SUBLET
      - MANUFACTURER
      - DEALER
    Price:
      type: object
      properties:
        display_value:
          type: string
          description: Human-readable display value for the pri...
        locale:
          type: string
          description: Locale used for formatting display value...
        value:
          type: string
          description: The numeric value of the price (before t...
        tax_value:
          type: string
          description: The calculated amount of tax applied to ...
        taxable_amount:
          type: string
          description: The portion of the price subject to tax.
        non_taxable_amount:
          type: string
          description: The portion of the price not subject to ...
        total_amount:
          type: string
          description: The total final price including all comp...
        total_cost_amount:
          type: string
          description: The total cost to the provider/seller.
        unit_cost_amount:
          type: string
          description: The unit cost to the provider/seller.
        price_description:
          type: string
          description: "A descriptive title for the price (e.g.,..."
        price_key:
          type: string
          description: Natural key or business identifier for t...
        tax_included_indicator:
          type: boolean
          description: Indicates whether tax is included in the...
        currency_code:
          type: string
          description: "ISO 4217 currency code, e.g., 'USD', 'EU..."
        price_id:
          type: string
          description: Unique system identifier for the price r...
        duration:
          $ref: "#/components/schemas/EffectivePeriod"
        price_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PriceTypes"
        pay_type:
          $ref: "#/components/schemas/PayTypes"
        currency_exchange:
          $ref: "#/components/schemas/CurrencyExchange"
      description: price.desc
    PriceTypes:
      type: string
      description: types of prices.
      enum:
      - METERED
      - SEAT
      - FLAT
      - ITEMIZED
      - BUNDLE
      - QUANTITY
      - PER_UNIT
      - PERCENT
      - VOLUME
      - USAGE
      - STAIR_STEP
      - SUBSCRIPTION
      - CUSTOM
      - STANDARD
      - LICENSED
      - TIER_VOLUME
      - TIER_GRADUATED
      - ACTUAL
      - LIST
      - RETAIL
      - MSRP
      - WHOLESALE
      - DEALER
      - TRADE
      - CORE
      - LANDED
      - PROMOTIONAL
      - DISCOUNT
      - CONTRACT
      - SALE
      - CUSTOMER
      - AFFILIATE
      - ONLINE
      - STORE
      - REGION
      - LOCATION
      - ESTIMATED
      - NET
      - PURCHASE
      - MONEY
      - TAXABLE
      - NONTAXABLE
      - TOTAL
      - UNIT
      - TOTAL_COST
      - UNIT_COST
      - TAX
      - OTHER
    Program:
      type: object
      properties:
        program_key:
          type: string
          description: The unique key for the program  record.
        program_id:
          type: string
          description: The unique id for the program  record.
        program_code:
          type: string
          description: The unique code for the .
        program_name:
          type: string
          description: The name of the .
        program_oem:
          type: string
          description: The value of the owner.
        description:
          type: string
          description: A description of the .
        program_type:
          $ref: "#/components/schemas/ProgramTypes"
      description: not nullable
    ProgramTypes:
      type: string
      description: types of programs.
      enum:
      - BILL_EXTENDED_TERM
      - BILL_NET_30
    DurationUOMTypes:
      type: string
      description: Units of Measure for Durations
      enum:
      - MINUTES
      - HOURS
      - DAYS
      - DAY_OF_MONTH
      - WEEKS
      - BI_WEEKS
      - SEMI_MONTHS
      - MONTHS
      - QUARTERS
      - SEMI_YEARS
      - YEARS
      - MULTI_YEARS
      - CUSTOM
      - OCCURRENCE
      - UNLIMITED
      - NONE
      - OTHER
