---
openapi: "3.0.1"
info:
  title: "Automotive Retail Systems API"
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: "Platform Architecture Team"
    url: "www.starstandard.org"
    email: "pescobar@starstandard.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    FinancialSplitReference:
      type: "object"
      properties:
        financial_split_reference_id:
          type: "string"
          description: "Unique identifier value for the referenc..."
        financial_split_reference_key:
          type: "string"
          description: "Unique key value for the reference recor..."
        financial_split_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "The unique key identifying the reference..."
        context:
          type: "string"
          description: "Context or domain of the payment financi..."
        identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the financialSplit was..."
          format: "date-time"
      description: "financial.split.reference.desc"
      types:
      - "object"
    FinancialSplitReferences:
      type: "array"
      items:
        $ref: "#/components/schemas/FinancialSplitReference"
    GeographicBoundaryReference:
      type: "object"
      properties:
        geographic_boundary_reference_id:
          type: "string"
          description: "Unique identifier value for the referenc..."
        geographic_boundary_reference_key:
          type: "string"
          description: "Unique key value for the reference recor..."
        geographic_boundary_key:
          type: "string"
          description: "The unique key identifying the reference..."
        context:
          type: "string"
          description: "Context or domain of the payment schedul..."
        identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the schedule was assoc..."
          format: "date-time"
      description: "geographic.boundary.reference.desc"
      types:
      - "object"
    GeographicBoundaryReferences:
      type: "array"
      items:
        $ref: "#/components/schemas/GeographicBoundaryReference"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value"
        identifier_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Business key for the identifier"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "Unique identification key for the record."
      types:
      - "object"
    List:
      type: "array"
      items:
        $ref: "#/components/schemas/PriceTypes"
    PriceClassTypes:
      type: "string"
      description: "types of price class."
      enum:
      - "NEW_CUSTOMER"
      - "LOYALTY_MEMBER"
      - "GOVERNMENT"
      - "ENTERPRISE"
      - "EDUCATIONAL"
      - "SCHEDULE"
      - "SOLD_PRICE"
      - "MSRP"
      - "OFFER"
      - "RETAIL"
      - "TRANSFER_COST"
      - "SUBLET_CHARGE"
      - "CHARGE_AMOUNT"
      - "LABOR_COST"
      - "PARTS_COST"
      - "SERVICE_COST"
      - "MATERIAL_COST"
      - "EXPENSE_COST"
      - "PRODUCTION_COST"
      - "COMMERCIAL_COST"
      - "DIRECT_COST"
      - "INDIRECT_COST"
      - "CALCULATED_COST"
      - "EXPENSE"
      - "CO_INSURANCE"
      - "CO_PAYMENT"
      - "INVOICE"
      - "DEDUCTIBLE"
      - "SUB_TOTAL"
      - "PERCENTAGE"
      - "HANDLING"
      - "TOTAL"
      - "APPROVED"
      - "PRORATED"
      - "PAID"
      - "REFUND"
      - "REQUESTED"
      - "OTHER"
    PricePlan:
      type: "object"
      properties:
        price_plan_id:
          type: "string"
          description: "Unique identifier for the price plan."
        price_plan_key:
          type: "string"
          description: "Unique identifier for the price plan."
        price_description:
          type: "string"
          description: "Description of the price plan."
        price_sensitivity:
          $ref: "#/components/schemas/PriceSensitivity"
        price_class_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          items:
            $ref: "#/components/schemas/PriceClassTypes"
          types:
          - "array"
        locale:
          type: "string"
          description: "Locale information for regional pricing."
        currency:
          type: "string"
          description: "Currency code for the price (ISO 4217)."
        codes:
          $ref: "#/components/schemas/Codes"
        price_group:
          type: "string"
          description: "Group categorization for pricing."
        price_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: "array"
          items:
            $ref: "#/components/schemas/PriceTypes"
          types:
          - "array"
        geographic_boundaries:
          $ref: "#/components/schemas/GeographicBoundaryReferences"
        financial_splits:
          $ref: "#/components/schemas/FinancialSplitReferences"
        schedules:
          $ref: "#/components/schemas/ProductScheduleReferences"
        resource_types:
          $ref: "#/components/schemas/ResourceTypes"
      description: "price.plan.desc"
      types:
      - "object"
    PriceSensitivity:
      type: "object"
      properties:
        price_sensitivity_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier for the price sensitiv..."
        price_sensitivity_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Business key for the price sensitivity c..."
        sensitivity_level_types:
          $ref: "#/components/schemas/PriceSensitivityTypes"
        quantity_level_types:
          $ref: "#/components/schemas/PriceSensitivityTypes"
        description:
          type: "string"
          description: "Description of this price sensitivity cl..."
        alias:
          $ref: "#/components/schemas/Codes"
      description: "nullable"
      types:
      - "object"
    PriceSensitivityTypes:
      type: "string"
      description: "types of price sensitivitys."
      enum:
      - "LOW"
      - "MEDIUM"
      - "HIGH"
      - "ELASTIC"
      - "INELASTIC"
    PriceTypes:
      type: "string"
      description: "types of prices."
      enum:
      - "METERED"
      - "SEAT"
      - "FLAT"
      - "ITEMIZED"
      - "BUNDLE"
      - "QUANTITY"
      - "PER_UNIT"
      - "PERCENT"
      - "VOLUME"
      - "USAGE"
      - "STAIR_STEP"
      - "SUBSCRIPTION"
      - "CUSTOM"
      - "STANDARD"
      - "LICENSED"
      - "TIER_VOLUME"
      - "TIER_GRADUATED"
      - "ACTUAL"
      - "LIST"
      - "RETAIL"
      - "MSRP"
      - "WHOLESALE"
      - "DEALER"
      - "TRADE"
      - "CORE"
      - "LANDED"
      - "PROMOTIONAL"
      - "DISCOUNT"
      - "CONTRACT"
      - "SALE"
      - "CUSTOMER"
      - "AFFILIATE"
      - "ONLINE"
      - "STORE"
      - "REGION"
      - "LOCATION"
      - "ESTIMATED"
      - "NET"
      - "PURCHASE"
      - "MONEY"
      - "TAXABLE"
      - "NONTAXABLE"
      - "TOTAL"
      - "UNIT"
      - "TOTAL_COST"
      - "UNIT_COST"
      - "TAX"
      - "OTHER"
    ProductScheduleReference:
      type: "object"
      properties:
        schedule_reference_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value for the referenc..."
        schedule_reference_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique key value for the reference recor..."
        schedule_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "The unique key identifying the reference..."
        context:
          type: "string"
          description: "Context or domain of the payment schedul..."
        identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the schedule was assoc..."
          format: "date-time"
      description: "product.schedule.reference.desc"
      types:
      - "object"
    ProductScheduleReferences:
      type: "array"
      items:
        $ref: "#/components/schemas/ProductScheduleReference"
    ResourceTypes:
      type: "string"
      description: "types of resources."
      enum:
      - "SYSTEM"
      - "WORKFLOW"
      - "ACTIVITY"
      - "FUNCTION"
      - "PROCESS"
      - "INCIDENT"
      - "PARTY"
      - "CUSTOMER"
      - "APPLICANT"
      - "VENDOR"
      - "DEALER_STAFF"
      - "DRIVER"
      - "ADDRESS"
      - "BILL_ADDRESS"
      - "BILL_CONTACT"
      - "COMM_CHANNEL"
      - "ACCOUNT"
      - "VEHICLE"
      - "TRADE_IN"
      - "PRODUCT"
      - "MANUFACTURER"
      - "LEAD"
      - "OPPORTUNITY"
      - "DEAL"
      - "FINANCE"
      - "INVOICE"
      - "LINEITEM"
      - "EXPENSE"
      - "DISCOUNT"
      - "TAX"
      - "FEE"
      - "INCENTIVE"
      - "DEALERSHIP"
      - "APPOINTMENT"
      - "OTHER"
