openapi: 3.0.1
info:
  title: Automotive Retail Systems API
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: Platform Architecture Team
    url: www.starstandard.org
    email: pescobar@starstandard.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths: {}
components:
  schemas:
    Codes:
      type: array
      items:
        type: string
    Identifier:
      type: object
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          type: string
          description: Unique identifier value
        identifier_key:
          maxLength: 50
          minLength: 5
          type: string
          description: Business key for the identifier
        context:
          type: string
          description: Context or domain of the identifier
        value:
          type: string
          description: The monetary or hours-based value of the...
        detail:
          type: string
          description: The monetary or hours-based value of the...
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: identifier.desc
    IdentifierCreate:
      required:
      - identifier_key
      type: object
      description: Identifier Create for Post
      allOf:
      - $ref: "#/components/schemas/Identifier"
    IdentifierUpdate:
      type: object
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        context:
          type: string
          description: Context or domain of the identifier
        detail:
          type: string
          description: The monetary or hours-based value of the...
        value:
          type: string
          description: The monetary or hours-based value of the...
      description: Identifier Update for Patch and Put
    Identifiers:
      type: array
      items:
        $ref: "#/components/schemas/Identifier"
    PartConditionTypes:
      type: string
      description: types of part conditions.
      enum:
      - NEW
      - NEW_OLD_STOCK
      - REMANUFACTURED
      - REBUILT
      - REFURBISHED
      - USED
      - SALVAGE
      - DAMAGED_MINOR
      - DAMAGED_COSMETIC
      - SCRAP
      - COLLECTIBLE
      - OTHER
    PartIdentifier:
      type: object
      properties:
        part_identifier_key:
          type: string
          description: Unique key identifying the part identifi...
        part_identifier_id:
          type: string
          description: Unique identifier ID for the part identi...
        part_source:
          type: string
          description: Unique identifier ID for the source of t...
        part_identifier_type:
          $ref: "#/components/schemas/PartIdentifierTypes"
        part_identifier_value:
          type: string
          description: Value of the part identifier
        description:
          type: string
          description: Optional description for the part identi...
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        part_names:
          $ref: "#/components/schemas/PartNames"
        part_status_type:
          $ref: "#/components/schemas/PartStatusTypes"
      description: nullable
    PartIdentifierCreate:
      required:
      - part_identifier_key
      type: object
      description: PartIdentifier Create for Post
      allOf:
      - $ref: "#/components/schemas/PartIdentifier"
    PartIdentifierTypes:
      type: string
      description: types of part identifiers.
      enum:
      - VIN
      - SKU
      - UPCA
      - UPCE
      - ISBN
      - MPN
      - CONFIG_CODE
      - MFR_CODE
      - ALT_CODE
      - STOCK_NBR
      - UNIV_CODE
      - PRODUCT_CODE
      - CATALOG_CODE
      - NAME
      - NUMBER
      - PREFIX
      - COUNTRY_OF_ORIGIN_CODE
      - MODEL_CODE
      - MAKE_CODE
      - YEAR_CODE
      - MARKET_DIVISION_CODE
      - TRIM_CODE
      - STYLE_CODE
      - SUB_MODEL_CODE
      - ENGINE_CODE
      - TRANSMISSION_CODE
      - DRAWING_NUMBER
      - OTHER
    PartIdentifierUpdate:
      type: object
      properties:
        part_identifier_type:
          $ref: "#/components/schemas/PartIdentifierTypes"
        part_source:
          type: string
          description: Unique identifier ID for the source of t...
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        part_identifier_value:
          type: string
          description: Value of the part identifier
        description:
          type: string
          description: Optional description for the part identi...
        part_names:
          $ref: "#/components/schemas/PartNames"
        part_status_type:
          $ref: "#/components/schemas/PartStatusTypes"
      description: PartIdentifier Update for Patch and Put
    PartName:
      type: object
      properties:
        part_name_id:
          type: string
          description: Unique identifier for the part name
        part_name_key:
          type: string
          description: Business key for the part name
        part_prefix:
          $ref: "#/components/schemas/Codes"
        part_suffix:
          $ref: "#/components/schemas/Codes"
        description:
          type: string
          description: Description of the part name
        language:
          $ref: "#/components/schemas/Codes"
        locale:
          $ref: "#/components/schemas/Codes"
        alias:
          $ref: "#/components/schemas/Codes"
        long_name:
          $ref: "#/components/schemas/Codes"
        marketing_name:
          $ref: "#/components/schemas/Codes"
        part_name_type:
          $ref: "#/components/schemas/PartNameTypes"
        part_number:
          $ref: "#/components/schemas/Codes"
      description: nullable
    PartNameCreate:
      required:
      - part_name_key
      type: object
      description: PartName Create for Post
      allOf:
      - $ref: "#/components/schemas/PartName"
    PartNameTypes:
      type: string
      description: types of part names.
      enum:
      - GENERIC
      - MANUFACTURING
      - MARKETING
      - CORE
      - REMANUFACTURING
      - OEM
      - AFTERMARKET
      - SUPERSEDING
      - SUPERSEDED
    PartNameUpdate:
      type: object
      properties:
        part_name_type:
          $ref: "#/components/schemas/PartNameTypes"
        part_prefix:
          $ref: "#/components/schemas/Codes"
        marketing_name:
          $ref: "#/components/schemas/Codes"
        description:
          type: string
          description: Description of the part name
        alias:
          $ref: "#/components/schemas/Codes"
        part_number:
          $ref: "#/components/schemas/Codes"
        language:
          $ref: "#/components/schemas/Codes"
        part_suffix:
          $ref: "#/components/schemas/Codes"
        locale:
          $ref: "#/components/schemas/Codes"
        long_name:
          $ref: "#/components/schemas/Codes"
      description: PartName Update for Patch and Put
    PartNames:
      type: array
      items:
        $ref: "#/components/schemas/PartName"
    PartPriceCriteria:
      type: object
      properties:
        part_price_criteria_id:
          type: string
          description: Descriptive name or keyword for the part...
          example: Front Brake Rotor
        part_price_criteria_key:
          type: string
          description: Descriptive name or keyword for the part...
          example: Front Brake Rotor
        min_price:
          type: string
          description: Minimum price of the part.
          example: "10.00"
        max_price:
          type: string
          description: Maximum price of the part.
          example: "100.00"
        currency:
          type: string
          description: "Currency for price filtering (e.g., 'USD..."
          example: USD
        core_charge_applicable:
          type: boolean
          description: "If true, only parts with an applicable c..."
          example: true
        warranty_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/WarrantyTypes"
        price_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PriceTypes"
      description: part.price.criteria.desc
    PartPriceCriteriaCreate:
      required:
      - part_price_criteria_key
      type: object
      description: PartPriceCriteria Create for Post
      allOf:
      - $ref: "#/components/schemas/PartPriceCriteria"
    PartPriceCriteriaUpdate:
      type: object
      properties:
        max_price:
          type: string
          description: Maximum price of the part.
          example: "100.00"
        min_price:
          type: string
          description: Minimum price of the part.
          example: "10.00"
        price_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PriceTypes"
        core_charge_applicable:
          type: boolean
          description: "If true, only parts with an applicable c..."
          example: true
        warranty_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/WarrantyTypes"
        currency:
          type: string
          description: "Currency for price filtering (e.g., 'USD..."
          example: USD
      description: PartPriceCriteria Update for Patch and Put
    PartSearch:
      type: object
      properties:
        part_search_id:
          type: string
          description: The status of the search operation.
          example: SUCCESS
        part_search_key:
          type: string
          description: The status of the search operation.
          example: SUCCESS
        part_search_criteria_key:
          type: string
          description: The status of the search operation.
          example: SUCCESS
        search_status:
          type: string
          description: The status of the search operation.
          example: SUCCESS
        results_count:
          type: integer
          description: The number of PartSearchResult items ret...
          format: int32
          example: 1
        part_search_results:
          $ref: "#/components/schemas/PartSearchResults"
        warehouses:
          $ref: "#/components/schemas/Identifiers"
      description: part.search.desc
    PartSearchCreate:
      required:
      - part_search_key
      type: object
      description: PartSearch Create for Post
      allOf:
      - $ref: "#/components/schemas/PartSearch"
    PartSearchResult:
      type: object
      properties:
        part_search_result_id:
          type: string
          description: Unique identifier for the part (can be m...
          example: PM_45678
        part_search_result_key:
          type: string
          description: Unique identifier for the part (can be m...
          example: PM_45678
        part_key:
          type: string
          description: Unique identifier for the part (can be m...
          example: PM_45678
        is_master_record:
          type: boolean
          description: Indicates if this result represents the ...
          example: true
        part_identifiers:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PartIdentifier"
        part_names:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PartName"
        part_condition_type:
          $ref: "#/components/schemas/PartConditionTypes"
        quantity_available:
          type: integer
          description: The total quantity available across all ...
          format: int32
          example: 1700
        primary_warehouse:
          $ref: "#/components/schemas/Identifier"
        part_price:
          $ref: "#/components/schemas/PartPriceCriteria"
        bill_of_material:
          $ref: "#/components/schemas/Identifier"
        part_status_type:
          $ref: "#/components/schemas/PartStatusTypes"
        estimated_availability_date:
          type: string
          description: The earliest date/time this part is expe...
          format: date
        origin_latitude:
          type: string
          description: Latitude of the part's physical location...
        origin_longitude:
          type: string
          description: Longitude of the part's physical locatio...
        shipping_method_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/ShippingMethodTypes"
      description: part.search.result.desc
    PartSearchResultCreate:
      required:
      - part_search_result_key
      type: object
      description: PartSearchResult Create for Post
      allOf:
      - $ref: "#/components/schemas/PartSearchResult"
    PartSearchResultUpdate:
      type: object
      properties:
        origin_longitude:
          type: string
          description: Longitude of the part's physical locatio...
        estimated_availability_date:
          type: string
          description: The earliest date/time this part is expe...
          format: date
        shipping_method_types:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/ShippingMethodTypes"
        bill_of_material:
          $ref: "#/components/schemas/Identifier"
        part_identifiers:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PartIdentifier"
        origin_latitude:
          type: string
          description: Latitude of the part's physical location...
        is_master_record:
          type: boolean
          description: Indicates if this result represents the ...
          example: true
        part_condition_type:
          $ref: "#/components/schemas/PartConditionTypes"
        part_price:
          $ref: "#/components/schemas/PartPriceCriteria"
        primary_warehouse:
          $ref: "#/components/schemas/Identifier"
        part_names:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PartName"
        part_status_type:
          $ref: "#/components/schemas/PartStatusTypes"
        quantity_available:
          type: integer
          description: The total quantity available across all ...
          format: int32
          example: 1700
      description: PartSearchResult Update for Patch and Put
    PartSearchResults:
      type: array
      items:
        $ref: "#/components/schemas/PartSearchResult"
    PartSearchUpdate:
      type: object
      properties:
        search_status:
          type: string
          description: The status of the search operation.
          example: SUCCESS
        results_count:
          type: integer
          description: The number of PartSearchResult items ret...
          format: int32
          example: 1
        warehouses:
          $ref: "#/components/schemas/Identifiers"
        part_search_results:
          $ref: "#/components/schemas/PartSearchResults"
      description: PartSearch Update for Patch and Put
    PartStatusTypes:
      type: string
      description: types of part status.
      enum:
      - RECEIVE
      - INSPECT_INBOUND
      - DOCUMENT_RECEIPT
      - PUTAWAY
      - QUARANTINE_INBOUND
      - PICK
      - PACK
      - STAGE_SHIPMENT
      - LOAD_SHIPMENT
      - SHIP
      - DOCUMENT_SHIPMENT
      - SCRAP_DISPOSE
      - DISASSEMBLE
      - RETURN_RECEIVE
      - RETURN_INSPECT
      - RETURN_PUTAWAY
      - REFURBISH_REPAIR
      - RETURN_TO_BIN
      - DEFECTIVE_REMOVAL
      - ALLOCATE_TO_JOB
      - PICK_FOR_LABOR
      - STAGE_FOR_SERVICE
      - ISSUE_TO_TECH
      - INSTALLED
      - CORE_PENDING
      - CORE_RECEIVED
      - CROSS_DOCK
      - LABEL_TAG
      - KIT_ASSEMBLE
      - VALUE_ADDED_SERVICE
      - SUPERSEDE
      - SUPERSEDED
    PriceTypes:
      type: string
      description: types of prices.
      enum:
      - METERED
      - SEAT
      - FLAT
      - ITEMIZED
      - BUNDLE
      - QUANTITY
      - PER_UNIT
      - PERCENT
      - VOLUME
      - USAGE
      - STAIR_STEP
      - SUBSCRIPTION
      - CUSTOM
      - STANDARD
      - LICENSED
      - TIER_VOLUME
      - TIER_GRADUATED
      - ACTUAL
      - LIST
      - RETAIL
      - MSRP
      - WHOLESALE
      - DEALER
      - TRADE
      - CORE
      - LANDED
      - PROMOTIONAL
      - DISCOUNT
      - CONTRACT
      - SALE
      - CUSTOMER
      - AFFILIATE
      - ONLINE
      - STORE
      - REGION
      - LOCATION
      - ESTIMATED
      - NET
      - PURCHASE
      - MONEY
      - TAXABLE
      - NONTAXABLE
      - TOTAL
      - UNIT
      - TOTAL_COST
      - UNIT_COST
      - TAX
      - OTHER
    ShippingMethodTypes:
      type: string
      description: types of shipping methods.
      enum:
      - OVERNIGHT
      - GROUND
      - LOCAL_DELIVERY
      - TWO_DAY_AIR
      - THREE_DAY_SELECT
      - EXPRESS
      - INTERNATIONAL_STANDARD
      - INTERNATIONAL_EXPEDITED
      - FREIGHT
      - DOWNLOAD
      - PALLET_DELIVERY
      - PICKUP
      - SAME_DAY
      - ECONOMY
      - HAZMAT
      - TEMPERATURE_CONTROLLED
      - FREE_SHIPPING
      - FLAT_RATE
      - TABLE_RATE
      - CURBSIDE_PICKUP
      - LOCKER_DELIVERY
      - ECO_FRIENDLY
      - HYBRID_SHIPPING
      - AIR_FREIGHT
      - OCEAN_FREIGHT
      - RAIL_FREIGHT
    WarrantyTypes:
      type: string
      description: types of warrantys.
      enum:
      - MANUFACTURER
      - DEALER
      - EXTENDED
      - CERTIFIED_PRE_OWNED
      - POWERTRAIN
      - CORROSION
      - HYBRID_EV_COMPONENT
      - LIMITED
      - LIFETIME
      - NO_WARRANTY
      - OTHER
