---
openapi: "3.0.1"
info:
  title: "Automotive Retail Systems API"
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: "Platform Architecture Team"
    url: "www.starstandard.org"
    email: "pescobar@starstandard.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.0"
paths: {}
components:
  schemas:
    Codes:
      type: "array"
      items:
        type: "string"
    Identifier:
      type: "object"
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value"
        identifier_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Business key for the identifier"
        context:
          type: "string"
          description: "Context or domain of the identifier"
        value:
          type: "string"
          description: "The monetary or hours-based value of the..."
        detail:
          type: "string"
          description: "The monetary or hours-based value of the..."
        identifier_type:
          type: "string"
          description: "The monetary or hours-based value of the..."
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: "Unique identification key for the record."
      types:
      - "object"
    Money:
      type: "object"
      properties:
        money_key:
          type: "string"
          description: "The unique key for the monetary value."
        money_id:
          type: "string"
          description: "The unique ID for the monetary value."
        currency_code:
          type: "string"
          description: "ISO currency code, e.g., 'USD'."
        display_value:
          type: "string"
          description: "The locale-specific display format for t..."
        locale:
          type: "string"
          description: "The locale code (e.g., en-US, fr-FR)."
        value:
          type: "string"
          description: "The monetary value."
      description: "Monetary value and currency information."
      types:
      - "object"
    Payment:
      type: "object"
      properties:
        payment_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value for the referenc..."
        payment_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique key value for the reference recor..."
        payment_transactions:
          $ref: "#/components/schemas/PaymentTransactions"
        target_amount:
          $ref: "#/components/schemas/Money"
        payment_status_type:
          $ref: "#/components/schemas/PaymentStatusTypes"
        context:
          type: "string"
          description: "Context or domain of the reference."
        occurrence_date_time:
          type: "string"
          description: "The date and time the payment was associ..."
          format: "date-time"
      description: "General payment record."
      types:
      - "object"
    PaymentAmountTypes:
      type: "string"
      description: "types of payment amounts."
      enum:
      - "PARTIAL_REFUND"
      - "TOTAL_REFUND"
      - "TOTAL_INTEREST"
      - "TOTAL_PAYMENT"
      - "TOTAL_PRINCIPAL"
      - "TOTAL_FINANCED"
      - "DOWN_PAYMENT"
      - "TRADE_IN_ALLOWANCE"
      - "CREDIT_CARD_PAYMENT"
      - "CASH_PAYMENT"
      - "CHECK_PAYMENT"
      - "EFT_PAYMENT"
      - "PAYMENT_EVENT"
      - "SCHEDULED_PAYMENT_EVENT"
      - "BASE_PAYMENT_EVENT"
      - "DESIRED_PAYMENT"
      - "ADMIN_FEE"
      - "GOVERNMENT_FEE"
      - "SERVICE_FEE"
      - "LATE_FEE"
      - "PAYROLL"
      - "OTHER"
    PaymentMethodReference:
      type: "object"
      properties:
        payment_method_reference_id:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique identifier value for the referenc..."
        payment_method_reference_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "Unique key value for the reference recor..."
        payment_method_key:
          maxLength: 50
          minLength: 5
          type: "string"
          description: "The unique key identifying the reference..."
        context:
          type: "string"
          description: "Context or domain of the reference."
        payment_method_type:
          $ref: "#/components/schemas/PaymentMethodTypes"
        processor_options:
          $ref: "#/components/schemas/Identifier"
        snapshot_details:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: "string"
          description: "The date and time the paymentMethod was ..."
          format: "date-time"
      description: "Reference to the stored payment method."
      types:
      - "object"
    PaymentMethodTypes:
      type: "string"
      description: "types of payment methods."
      enum:
      - "CASH"
      - "CHECK"
      - "MONEY_ORDER"
      - "CASH_ON_DELIVERY"
      - "CREDIT_CARD"
      - "DEBIT_CARD"
      - "GIFT_CARD"
      - "EFT"
      - "ONLINE_BANK_TRANSFER"
      - "MOBILE_WALLET"
      - "CRYPTOCURRENCY"
      - "ONLINE_PAYMENT_PLATFORM"
      - "PAYROLL_DEDUCTION"
      - "FINANCE"
      - "LEASE"
      - "RENTAL"
      - "TERMS"
      - "DUE_ON_RECEIPT"
      - "TRADE_IN"
      - "REWARD_POINTS"
      - "STORE_CREDIT"
      - "EXCHANGE"
      - "OTHER"
      - "NOT_APPLICABLE"
    PaymentStatusTypes:
      type: "string"
      description: "types of payment status."
      enum:
      - "CREATED"
      - "PENDING"
      - "PROCESSING"
      - "PROCESSED"
      - "COMPLETED"
      - "SUCCEEDED"
      - "PAID"
      - "REJECTED"
      - "SCHEDULED"
      - "SUBMITTED"
      - "DEFERRED"
      - "DEFERRED_INTERNAL"
      - "CLEARED"
      - "FRAUD_REVIEW"
      - "APPROVED"
      - "ACCEPTED"
      - "REQUIRES_ACTION"
      - "REQUIRES_PAYMENT_STATUS"
      - "AUTO_SCHEDULED"
      - "AUTO_INITIATED"
      - "MANUAL_INITIATED"
      - "PENDING_PAYER_FUNDS"
      - "FAILED"
      - "DENIED"
      - "EXPIRED"
      - "CANCELLED"
      - "VOIDED"
      - "REVERSED"
      - "REFUNDED"
      - "PAYROLL_PENDING"
      - "PAYROLL_FINALIZED"
      - "ACTIVE"
      - "INACTIVE"
      - "FUNDED"
      - "RETURNED"
    PaymentTransaction:
      type: "object"
      properties:
        payment_amount_key:
          type: "string"
          description: "A unique key for the payment amount."
        payment_amount_id:
          type: "string"
          description: "A unique key for the payment amount."
        payment_amount_type:
          $ref: "#/components/schemas/PaymentAmountTypes"
        payment_method_reference:
          $ref: "#/components/schemas/PaymentMethodReference"
        amount:
          $ref: "#/components/schemas/Money"
        payment_transaction_status_type:
          $ref: "#/components/schemas/PaymentTransactionStatusTypes"
      description: "Specific processing details of a payment."
      types:
      - "object"
    PaymentTransactionStatusTypes:
      type: "string"
      description: "types of payment transaction status."
      enum:
      - "NONE"
      - "EXPIRED"
      - "CAPTURED"
      - "CONFIRMATION"
      - "VOID"
      - "APPROVE"
      - "REFUNDED"
      - "PARTIALLY_REFUNDED"
      - "AUTHORIZE"
      - "PENDING_MERCHANT"
      - "SUSPENDED"
      - "OPEN"
      - "PEND"
      - "PROCESS"
      - "DECLINE"
      - "DUE"
      - "INCURRED"
      - "CUSTOM_CODE"
      - "USER_HOLD"
      - "ADMIN_HOLD"
      - "ACTIVATED"
      - "DEACTIVATE"
      - "CANCEL"
      - "CONFIRM"
      - "CLOSE"
      - "TRIAL"
      - "SUBSCRIPTION"
      - "OVERRIDE"
      - "UPGRADE"
      - "HOLD_ON_RENEWAL"
      - "HOLD_ON_DATE"
      - "PAYMENT"
      - "DOWNGRADE"
    PaymentTransactions:
      type: "array"
      items:
        $ref: "#/components/schemas/PaymentTransaction"
