openapi: 3.0.1
info:
  title: Automotive Retail Systems API
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: Platform Architecture Team
    url: www.starstandard.org
    email: pescobar@starstandard.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths: {}
components:
  schemas:
    AccountingPeriod:
      type: object
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        period_desc:
          type: string
          description: Descriptive name for the accounting peri...
        accounting_period_id:
          type: string
          description: Business key for the accounting period (...
        accounting_period_key:
          type: string
          description: Business key for the accounting period (...
        period_name:
          type: string
          description: Display name of the accounting period.
        start_date:
          type: string
          description: The beginning date of the accounting per...
          format: date
        end_date:
          type: string
          description: The ending date of the accounting period...
          format: date
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        fiscal_year:
          type: integer
          description: The fiscal year this period belongs to.
          format: int32
      description: The fiscal timeframe used for reporting and auditing.
    AccountingPeriodCreate:
      required:
      - accounting_period_key
      type: object
      description: AccountingPeriod Create for Post
      allOf:
      - $ref: "#/components/schemas/AccountingPeriod"
    AccountingPeriodStatusTypes:
      type: string
      description: types of accounting period status.
      enum:
      - OPEN
      - ADJUSTMENT
      - CLOSED
      - FUTURE
      - PENDING_CLOSURE
      - LOCKED
      - OTHER
    AccountingPeriodUpdate:
      type: object
      properties:
        end_date:
          type: string
          description: The ending date of the accounting period...
          format: date
        period_desc:
          type: string
          description: Descriptive name for the accounting peri...
        fiscal_year:
          type: integer
          description: The fiscal year this period belongs to.
          format: int32
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        period_name:
          type: string
          description: Display name of the accounting period.
        start_date:
          type: string
          description: The beginning date of the accounting per...
          format: date
      description: AccountingPeriod Update for Patch and Put
    CashFlowLineItem:
      type: object
      properties:
        cash_flow_line_item_id:
          type: string
          description: The unique key for the Cash Flow LineIte...
        cash_flow_line_item_key:
          type: string
          description: The unique key for the Cash Flow LineIte...
        period_start_date:
          type: string
          description: The start date of the reporting period f...
          format: date
        period_end_date:
          type: string
          description: The end date of the reporting period for...
          format: date
        cash_inflow_total:
          $ref: "#/components/schemas/Money"
        cash_outflow_total:
          $ref: "#/components/schemas/Money"
        net_cash_flow:
          $ref: "#/components/schemas/Money"
        cash_balance_closing:
          $ref: "#/components/schemas/Money"
        source_category:
          type: string
          description: The source type or category for this flo...
      description: A specific entry in a cash flow statement.
    CashFlowLineItemCreate:
      required:
      - cash_flow_line_item_key
      type: object
      description: CashFlowLineItem Create for Post
      allOf:
      - $ref: "#/components/schemas/CashFlowLineItem"
    CashFlowLineItemUpdate:
      type: object
      properties:
        net_cash_flow:
          $ref: "#/components/schemas/Money"
        period_end_date:
          type: string
          description: The end date of the reporting period for...
          format: date
        cash_balance_closing:
          $ref: "#/components/schemas/Money"
        period_start_date:
          type: string
          description: The start date of the reporting period f...
          format: date
        cash_outflow_total:
          $ref: "#/components/schemas/Money"
        source_category:
          type: string
          description: The source type or category for this flo...
        cash_inflow_total:
          $ref: "#/components/schemas/Money"
      description: CashFlowLineItem Update for Patch and Put
    CashFlowLineItems:
      type: array
      items:
        $ref: "#/components/schemas/CashFlowLineItem"
    CashFlowProjection:
      type: object
      properties:
        cash_flow_projection_key:
          type: string
          description: The unique key for the Cash Flow Project...
        cash_flow_projection_id:
          type: string
          description: The unique key for the Cash Flow Project...
        cash_flow_projection_criteria:
          $ref: "#/components/schemas/CashFlowProjectionCriteria"
        projection_date:
          type: string
          description: The date the projection was generated.
          format: date
        cash_balance_opening:
          $ref: "#/components/schemas/Money"
        scenario:
          $ref: "#/components/schemas/CashFlowScenario"
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
        line_items:
          $ref: "#/components/schemas/CashFlowLineItems"
      description: Forecasted movement of cash into and out of the business.
    CashFlowProjectionCreate:
      required:
      - cash_flow_projection_key
      type: object
      description: CashFlowProjection Create for Post
      allOf:
      - $ref: "#/components/schemas/CashFlowProjection"
    CashFlowProjectionCriteria:
      type: object
      properties:
        budget_variance_report_request_id:
          type: string
          description: The Accounting Period Key for which the ...
        budget_variance_report_request_key:
          type: string
          description: The Accounting Period Key for which the ...
        period_granularity_type:
          $ref: "#/components/schemas/UOMTimeTypes"
        scenario_key:
          type: string
          description: Optional key of a pre-defined CashFlowSc...
        accounting_period_key:
          type: string
          description: The Accounting Period Key for which the ...
        gl_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        control_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        organization_id:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        start_date:
          type: string
          description: The start date for the forecast period (...
          format: date
        end_date:
          type: string
          description: The end date for the forecast period (in...
          format: date
        opening_cash_balance:
          $ref: "#/components/schemas/Money"
      description: Parameters for calculating cash projections.
    CashFlowProjectionCriteriaCreate:
      required:
      - cash_flow_projection_criteria_key
      type: object
      description: CashFlowProjectionCriteria Create for Post
      allOf:
      - $ref: "#/components/schemas/CashFlowProjectionCriteria"
    CashFlowProjectionCriteriaUpdate:
      type: object
      properties:
        period_granularity_type:
          $ref: "#/components/schemas/UOMTimeTypes"
        end_date:
          type: string
          description: The end date for the forecast period (in...
          format: date
        opening_cash_balance:
          $ref: "#/components/schemas/Money"
        gl_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        control_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        start_date:
          type: string
          description: The start date for the forecast period (...
          format: date
      description: CashFlowProjectionCriteria Update for Patch and Put
    CashFlowProjectionUpdate:
      type: object
      properties:
        scenario:
          $ref: "#/components/schemas/CashFlowScenario"
        cash_balance_opening:
          $ref: "#/components/schemas/Money"
        cash_flow_projection_criteria:
          $ref: "#/components/schemas/CashFlowProjectionCriteria"
        line_items:
          $ref: "#/components/schemas/CashFlowLineItems"
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
        projection_date:
          type: string
          description: The date the projection was generated.
          format: date
      description: CashFlowProjection Update for Patch and Put
    CashFlowScenario:
      type: object
      properties:
        scenario_key:
          type: string
          description: The unique key for the Cash Flow Scenari...
        name:
          type: string
          description: A user-friendly name for the scenario (e...
        ar_collection_delay_days:
          type: integer
          description: The average number of days past due date...
          format: int32
        ap_payment_hold_days:
          type: integer
          description: The average number of days the business ...
          format: int32
        description:
          type: string
          description: A description of the assumptions used in...
      description: not nullable
    CashFlowScenarioCreate:
      required:
      - cash_flow_scenario_key
      type: object
      description: CashFlowScenario Create for Post
      allOf:
      - $ref: "#/components/schemas/CashFlowScenario"
    CashFlowScenarioUpdate:
      type: object
      properties:
        ar_collection_delay_days:
          type: integer
          description: The average number of days past due date...
          format: int32
        name:
          type: string
          description: A user-friendly name for the scenario (e...
        description:
          type: string
          description: A description of the assumptions used in...
        ap_payment_hold_days:
          type: integer
          description: The average number of days the business ...
          format: int32
      description: CashFlowScenario Update for Patch and Put
    Codes:
      type: array
      items:
        type: string
    Identifier:
      type: object
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          type: string
          description: Unique identifier value
        identifier_key:
          maxLength: 50
          minLength: 5
          type: string
          description: Business key for the identifier
        context:
          type: string
          description: Context or domain of the identifier
        value:
          type: string
          description: The monetary or hours-based value of the...
        detail:
          type: string
          description: The monetary or hours-based value of the...
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: Unique identification key for the record.
    IdentifierCreate:
      required:
      - identifier_key
      type: object
      description: Identifier Create for Post
      allOf:
      - $ref: "#/components/schemas/Identifier"
    IdentifierUpdate:
      type: object
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        context:
          type: string
          description: Context or domain of the identifier
        detail:
          type: string
          description: The monetary or hours-based value of the...
        value:
          type: string
          description: The monetary or hours-based value of the...
      description: Identifier Update for Patch and Put
    Identifiers:
      type: array
      items:
        $ref: "#/components/schemas/Identifier"
    Money:
      type: object
      properties:
        money_key:
          type: string
          description: The unique key for the monetary value.
        money_id:
          type: string
          description: The unique ID for the monetary value.
        currency_code:
          type: string
          description: "ISO currency code, e.g., 'USD'."
        display_value:
          type: string
          description: The locale-specific display format for t...
        locale:
          type: string
          description: "The locale code (e.g., en-US, fr-FR)."
        value:
          type: string
          description: The monetary value.
      description: Monetary value and currency information.
    UOMTimeTypes:
      type: string
      description: types of u o m times.
      enum:
      - NANOSECOND
      - MICROSECOND
      - MILLISECOND
      - SECOND
      - MINUTE
      - HOUR
      - DAY
      - WEEK
      - MONTH
      - YEAR
      - DECADE
      - CENTURY
      - MILLENNIUM
      - PERCENTAGE_OF_HOUR
      - DURATION
      - MINUTES
      - HOURS
      - DAYS
      - WEEKS
      - DAY_OF_MONTH
      - BI_WEEKS
      - SEMI_MONTHS
      - MONTHS
      - QUARTERS
      - SEMI_YEARS
      - YEARS
      - MULTI_YEARS
      - OCCURRENCE
      - UNLIMITED
      - NONE
      - CUSTOM
      - OTHER
