openapi: 3.0.1
info:
  title: Automotive Retail Systems API
  description: "A standardized interface for Automotive Retail operations, built upon\
    \ a formal Retail Ontology. It enables seamless integration \n\n**Key Capabilities:**\n\
    * **Catalog Management:** Unified definitions for parts, assemblies, and BOMs.\n\
    * **Inventory Orchestration:** Real-time visibility into warehouse and dealership\
    \ stock.\n* **Financial Workflows:** Automated invoicing and batch processing\
    \ for high-volume retail transactions.\n\nDesigned for high-reliability CI/CD\
    \ environments and asynchronous batch processing."
  contact:
    name: Platform Architecture Team
    url: www.starstandard.org
    email: pescobar@starstandard.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}
components:
  schemas:
    AccountingPeriod:
      type: object
      properties:
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        period_desc:
          type: string
          description: Descriptive name for the accounting peri...
        accounting_period_id:
          pattern: "^[0-9]{6}$"
          type: string
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
        accounting_period_key:
          pattern: "^[0-9]{6}$"
          type: string
          description: "Business key for the accounting period (... Pattern: ^[0-9]{6}$\
            \ (Must be in YYYYMM format)"
        period_name:
          type: string
          description: Display name of the accounting period.
        start_date:
          type: string
          description: The beginning date of the accounting per...
          format: date
        end_date:
          type: string
          description: The ending date of the accounting period...
          format: date
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        fiscal_year:
          type: integer
          description: The fiscal year this period belongs to.
          format: int32
      description: The fiscal timeframe used for reporting and auditing.
    AccountingPeriodCreate:
      required:
      - accounting_period_key
      type: object
      description: AccountingPeriod Create for Post
      allOf:
      - $ref: "#/components/schemas/AccountingPeriod"
    AccountingPeriodStatusTypes:
      type: string
      description: types of accounting period status.
      enum:
      - OPEN
      - ADJUSTMENT
      - CLOSED
      - FUTURE
      - PENDING_CLOSURE
      - LOCKED
      - OTHER
    AccountingPeriodUpdate:
      type: object
      properties:
        end_date:
          type: string
          description: The ending date of the accounting period...
          format: date
        period_desc:
          type: string
          description: Descriptive name for the accounting peri...
        fiscal_year:
          type: integer
          description: The fiscal year this period belongs to.
          format: int32
        identifiers:
          $ref: "#/components/schemas/Identifiers"
        accounting_period_status_type:
          $ref: "#/components/schemas/AccountingPeriodStatusTypes"
        period_name:
          type: string
          description: Display name of the accounting period.
        start_date:
          type: string
          description: The beginning date of the accounting per...
          format: date
      description: AccountingPeriod Update for Patch and Put
    BudgetVarianceLineItem:
      type: object
      properties:
        budget_variance_line_item_id:
          type: string
          description: The unique ID for the report line item.
        budget_variance_line_item_key:
          type: string
          description: The unique ID for the report line item.
        general_ledger_account:
          $ref: "#/components/schemas/GeneralLedgerReference"
        control_account:
          $ref: "#/components/schemas/ControlAccountReference"
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
        budgeted_amount:
          $ref: "#/components/schemas/Money"
        actual_amount:
          $ref: "#/components/schemas/Money"
        variance_detail:
          $ref: "#/components/schemas/VarianceDetail"
      description: A specific line in a budget variance analysis.
    BudgetVarianceLineItemCreate:
      required:
      - budget_variance_line_item_key
      type: object
      description: BudgetVarianceLineItem Create for Post
      allOf:
      - $ref: "#/components/schemas/BudgetVarianceLineItem"
    BudgetVarianceLineItemUpdate:
      type: object
      properties:
        budgeted_amount:
          $ref: "#/components/schemas/Money"
        actual_amount:
          $ref: "#/components/schemas/Money"
        general_ledger_account:
          $ref: "#/components/schemas/GeneralLedgerReference"
        control_account:
          $ref: "#/components/schemas/ControlAccountReference"
        financial_category_type:
          $ref: "#/components/schemas/FinancialCategoryTypes"
        variance_detail:
          $ref: "#/components/schemas/VarianceDetail"
      description: BudgetVarianceLineItem Update for Patch and Put
    BudgetVarianceReport:
      type: object
      properties:
        budget_variance_report_id:
          type: string
          description: The unique ID for the generated report.
        budget_variance_report_key:
          type: string
          description: The unique ID for the generated report.
        budget_variance_report_criteria:
          $ref: "#/components/schemas/BudgetVarianceReportCriteria"
        report_date:
          type: string
          description: The date and time the report was generat...
          format: date
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
        line_items:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/BudgetVarianceLineItem"
      description: A report comparing planned budget vs actual spend.
    BudgetVarianceReportCreate:
      required:
      - budget_variance_report_key
      type: object
      description: BudgetVarianceReport Create for Post
      allOf:
      - $ref: "#/components/schemas/BudgetVarianceReport"
    BudgetVarianceReportCriteria:
      type: object
      properties:
        budget_variance_report_criteria_id:
          type: string
          description: The Accounting Period Key for which the ...
        budget_variance_report_criteria_key:
          type: string
          description: The Accounting Period Key for which the ...
        accounting_period_key:
          type: string
          description: The Accounting Period Key for which the ...
        gl_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        control_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        financial_categories:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/FinancialCategoryTypes"
        organization_id:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        min_variance_percentage:
          type: string
          description: Minimum absolute variance percentage to ...
      description: Criteria used to generate a variance report.
    BudgetVarianceReportCriteriaCreate:
      required:
      - budget_variance_report_criteria_key
      type: object
      description: BudgetVarianceReportCriteria Create for Post
      allOf:
      - $ref: "#/components/schemas/BudgetVarianceReportCriteria"
    BudgetVarianceReportCriteriaUpdate:
      type: object
      properties:
        gl_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        financial_categories:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/FinancialCategoryTypes"
        control_account_keys:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        min_variance_percentage:
          type: string
          description: Minimum absolute variance percentage to ...
      description: BudgetVarianceReportCriteria Update for Patch and Put
    BudgetVarianceReportUpdate:
      type: object
      properties:
        line_items:
          maxItems: 255
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/BudgetVarianceLineItem"
        budget_variance_report_criteria:
          $ref: "#/components/schemas/BudgetVarianceReportCriteria"
        accounting_period:
          $ref: "#/components/schemas/AccountingPeriod"
        report_date:
          type: string
          description: The date and time the report was generat...
          format: date
      description: BudgetVarianceReport Update for Patch and Put
    Codes:
      type: array
      items:
        type: string
    ControlAccountReference:
      type: object
      properties:
        control_account_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        control_account_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        control_account_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: string
          description: Context or domain of the identifier
        system_codes:
          $ref: "#/components/schemas/Codes"
        control_account:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: string
          description: The date and time the event occurred.
          format: date-time
      description: Reference link to the control account.
    ControlAccountReferenceCreate:
      required:
      - control_account_reference_key
      type: object
      description: ControlAccountReference Create for Post
      allOf:
      - $ref: "#/components/schemas/ControlAccountReference"
    ControlAccountReferenceUpdate:
      type: object
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        context:
          type: string
          description: Context or domain of the identifier
        control_account:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: string
          description: The date and time the event occurred.
          format: date-time
      description: ControlAccountReference Update for Patch and Put
    FinancialCategoryTypes:
      type: string
      description: types of financial categorys.
      enum:
      - CAPEX
      - OPEX
      - HARDWARE
      - SOFTWARE
      - MAINTENANCE
      - TRAVEL
      - TRAINING
      - UTILITIES
      - RENT
      - SALARY
      - REVENUE
      - TAX
      - OTHER
    GeneralLedgerReference:
      type: object
      properties:
        general_ledger_reference_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        general_ledger_reference_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        general_ledger_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique reference value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: string
          description: Context or domain of the reference
        system_codes:
          $ref: "#/components/schemas/Codes"
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
        occurrence_date_time:
          type: string
          description: The date and time the event occurred.
          format: date-time
      description: Reference to the primary General Ledger.
    GeneralLedgerReferenceCreate:
      required:
      - general_ledger_reference_key
      type: object
      description: GeneralLedgerReference Create for Post
      allOf:
      - $ref: "#/components/schemas/GeneralLedgerReference"
    GeneralLedgerReferenceUpdate:
      type: object
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        general_ledger_identifier:
          $ref: "#/components/schemas/Identifier"
        context:
          type: string
          description: Context or domain of the reference
        occurrence_date_time:
          type: string
          description: The date and time the event occurred.
          format: date-time
      description: GeneralLedgerReference Update for Patch and Put
    Identifier:
      type: object
      properties:
        identifier_id:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Unique identifier value Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        identifier_key:
          maxLength: 50
          minLength: 5
          pattern: "^[a-zA-Z0-9_]+$"
          type: string
          description: "Business key for the identifier Pattern: ^[a-zA-Z0-9_]+$ (Alphanumeric\
            \ and underscores allowed)"
        context:
          type: string
          description: Context or domain of the identifier
        value:
          type: string
          description: The monetary or hours-based value of the...
        detail:
          type: string
          description: The monetary or hours-based value of the...
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        system_codes:
          $ref: "#/components/schemas/Codes"
      description: Unique identification key for the record.
    IdentifierCreate:
      required:
      - identifier_key
      type: object
      description: Identifier Create for Post
      allOf:
      - $ref: "#/components/schemas/Identifier"
    IdentifierUpdate:
      type: object
      properties:
        system_codes:
          $ref: "#/components/schemas/Codes"
        identifier_type:
          type: string
          description: The monetary or hours-based value of the...
        context:
          type: string
          description: Context or domain of the identifier
        detail:
          type: string
          description: The monetary or hours-based value of the...
        value:
          type: string
          description: The monetary or hours-based value of the...
      description: Identifier Update for Patch and Put
    Identifiers:
      type: array
      items:
        $ref: "#/components/schemas/Identifier"
    Money:
      type: object
      properties:
        money_key:
          type: string
          description: The unique key for the monetary value.
        money_id:
          type: string
          description: The unique ID for the monetary value.
        currency_code:
          type: string
          description: "ISO currency code, e.g., 'USD'."
        display_value:
          type: string
          description: The locale-specific display format for t...
        locale:
          type: string
          description: "The locale code (e.g., en-US, fr-FR)."
        value:
          type: string
          description: The monetary value.
      description: Monetary value and currency information.
    VarianceDetail:
      type: object
      properties:
        variance_amount:
          $ref: "#/components/schemas/Money"
        variance_percentage:
          type: string
          description: The variance expressed as a percentage o...
        favorable_indicator:
          type: boolean
          description: Indicator if the variance is favorable (...
      description: variance.detail.desc
    VarianceDetailCreate:
      required:
      - variance_detail_key
      type: object
      description: VarianceDetail Create for Post
      allOf:
      - $ref: "#/components/schemas/VarianceDetail"
    VarianceDetailUpdate:
      type: object
      properties:
        favorable_indicator:
          type: boolean
          description: Indicator if the variance is favorable (...
        variance_amount:
          $ref: "#/components/schemas/Money"
        variance_percentage:
          type: string
          description: The variance expressed as a percentage o...
      description: VarianceDetail Update for Patch and Put
